#Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mstream-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mruggeri-mstream.my.kube.um.edu.ar
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mstream-service
                port:
                  number: 80

---
#ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mstream-config
data:
  PUID: "1000" 
  PGID: "1000"
  TZ: "Etc/AR"

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: mstream-service
  labels:
    app: mstream
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: mstream

---
#StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mstream
  labels:
    app: mstream
spec:
  serviceName: "mstream"
  replicas: 1
  selector:
    matchLabels:
      app: mstream
  template:
    metadata:
      labels:
        app: mstream
    spec:
      initContainers:
      - name: init-music
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            wget -qO- https://github.com/Martin-Ruggeri-Ing/music/archive/refs/heads/main.zip | busybox unzip - -d /music
        volumeMounts:
          - name: music-storage
            mountPath: /music

      containers:
      - name: mstream
        image: linuxserver/mstream:5.12.2

        ports:
        - containerPort: 3000

        env:
          - name: PUID
            valueFrom:
              configMapKeyRef:
                name: mstream-config
                key: PUID

          - name: PGID
            valueFrom:
              configMapKeyRef:
                name: mstream-config
                key: PGID

          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: mstream-config
                key: TZ

        volumeMounts:
          - name: music-storage
            mountPath: /music

  volumeClaimTemplates:
  - metadata:
      name: music-storage
      labels:
        app: mstream
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
  
  - metadata:
      name: config-storage
      labels:
        app: mstream
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi