apiVersion: v1
data:
  metabase-db-dbname: bXlwb3N0Z3Jlcw== #mypostgres
  metabase-db-pass: bWFydGluX3Bhc3N3b3Jk #martin_password
  metabase-db-type: cG9zdGdyZXM= #postgres
  metabase-db-user: cG9zdGdyZXM= #postgres
kind: Secret
metadata:
  creationTimestamp: null
  name: metabase-secret
