#T* Deployment Metabase
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ruggeriml-dev
  name: metabase
  labels:
    app: metabase

spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase

  template:
    metadata:
      labels:
        app: metabase

    spec:

      containers:
        - name: metabase
          image: metabase/metabase:v0.48.6

          ports:
          - containerPort: 3000

          env:

            #! Variables de entorno de ConfigMap
            - name: MB_DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db-name

            - name: MB_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db-user

            - name: MB_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db-port

            - name: MB_DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db-type

            - name: MB_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db-host

            #! Variables de entorno de Secret
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-pass

---
#T* Service Metabase
apiVersion: v1
kind: Service
metadata:
  namespace: ruggeriml-dev
  name: metabase-service
  labels:
    app: metabase-service

spec:
  ports:
  - port: 3000 
    targetPort: 3000
    protocol: TCP
  selector:
    app: metabase
  type: LoadBalancer

---
#T* Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  name: metabase-ingress
  namespace: ruggeriml-dev
spec:
  rules:
  - host: ruggeriml-metabase.my.kube
    http:
      paths:
      - backend:
          service:
            name: metabase-service
            port:
              number: 3000
        path: /
        pathType: Prefix

#.um.edu.ar
