apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ruggeriml-dev
  name: db
  labels:
    run: db

spec:
  replicas: 1
  selector:
    matchLabels:
      run: db
  serviceName: "db"

  template:
    metadata:
      generateName: db
      labels:
        run: db

    spec:

      initContainers:
      - name: remove-lost-found
        image: busybox:1.25.0
        command: ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      
      - name: download-data
        image: curlimages/curl:7.74.0
        command: ["sh", "-c", "curl -L -o /docker-entrypoint-initdb.d/google-mobility.sql https://raw.githubusercontent.com/Martin-Ruggeri-Ing/datakube/main/google-mobility.sql"]
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d

      containers:
      - name: db-mobility
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: db
        env:

        #! Variables de entorno de ConfigMap
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: db-name

        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: db-user

        #! Variables de entorno de Secret
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-pass

        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true

      volumes:
      - name: init-sql
        emptyDir: {}
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data

  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi

status: 
  replicas: 1

---

#T* Service postgres
apiVersion: v1
kind: Service
metadata:
  name: db  #! Nombre.
  namespace: ruggeriml-dev
  labels:
    run: db  #! Etiqueta.

spec:
  selector: #! Pods a los que el servicio debe dirigir el tráfico.
    run: db
  ports:
    - port: 3306 #! Puerto del servicio.
      targetPort: 3306 #! Puerto del Pod.
      protocol: TCP

