#T* ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ruggeriml-dev
  name: db-configmap

data:
  db-user: root
  db-name: metabase_mobility
  db-type: mysql
  db-port: "3306"
  db-host: mysql

---
#T* Secret
apiVersion: v1
kind: Secret
metadata:
  namespace: ruggeriml-dev
  creationTimestamp: null
  name: db-secret
data:
  db-pass: cGFzc19tb2JpbGl0eQ==  #pass_mobility