#T* ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ruggeriml-dev
  name: db-configmap

data:
  db-user: postgres
  db-name: metabase_mobility
  db-type: postgres
  db-port: "5432" #puerto de la base de datos
  db-host: db #nombre del servicio de la base de datos

---
#T* Secret
apiVersion: v1
kind: Secret
metadata:
  namespace: ruggeriml-dev
  creationTimestamp: null
  name: db-secret
data:
  db-pass: cGFzc19tb2JpbGl0eQ==  #pass_mobility