apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret
data:
  db-name: bWFydGluX2FwcA== #martin_app
  db-password: bWFydGluX3Bhc3N3b3Jk #martin_password
  db-username: cm9vdA== #root
